In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fake-news/submit.csv
/kaggle/input/fake-news/train.csv
/kaggle/input/fake-news/test.csv


In [4]:
df=pd.read_csv('/kaggle/input/fake-news/train.csv')

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.shape

(20800, 5)

In [7]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [56]:
X=df.drop('label',axis=1)
y=df['label']

In [12]:
y.shape

(18285,)

In [13]:
message=X.copy()

In [15]:
message.columns

Index(['id', 'title', 'author', 'text'], dtype='object')

In [16]:
message.title[0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [17]:
import nltk
import re
from nltk.corpus import stopwords

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
from nltk.stem.porter import PorterStemmer

In [41]:
ps=PorterStemmer()
corpus=[]
for i in range(0,8000):
    ele=re.sub('[^a-zA-Z]',' ',message.title.iloc[i])
    ele=ele.lower()
    ele=ele.split()
    ele=[ps.stem(word) for word in ele if not word in stopwords.words('english')]
    ele=' '.join(ele)
    corpus.append(ele)


In [42]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [43]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [29]:
#Make one hot representation
from tensorflow.keras.preprocessing.text import one_hot
voc_size=5000

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

In [44]:
onehot_rep=[one_hot(word,voc_size) for word in corpus]
onehot_rep

[[2917, 800, 2480, 3317, 1126, 2940, 1455, 2304, 2257, 3417],
 [1306, 1525, 4361, 4499, 4060, 2210, 1180],
 [1849, 3384, 2267, 1674],
 [4529, 59, 3655, 938, 2521, 4690],
 [2761, 4060, 3042, 1167, 4131, 1480, 4060, 3023, 51, 2159],
 [262,
  1869,
  4719,
  4349,
  777,
  1551,
  4185,
  1659,
  4070,
  547,
  2805,
  476,
  3546,
  3541,
  1180],
 [3562, 165, 2690, 1470, 1635, 1080, 1092, 4381, 1804, 481, 4006],
 [4434, 4175, 2358, 2569, 3147, 802, 1551, 2643, 1804, 481, 4006],
 [1806, 3576, 241, 3850, 4026, 3377, 1457, 2018, 1551, 2456],
 [2361, 1882, 2957, 768, 2434, 3579, 1928, 471],
 [492, 906, 2315, 4468, 3870, 176, 26, 2556, 2882, 306, 4906],
 [938, 3901, 1126, 3377, 1551, 3147],
 [2733, 2993, 2879, 1268, 4962, 3935, 1393, 4743, 1983],
 [108, 3028, 1904, 2321, 3893, 1221, 3281, 1804, 481, 4006],
 [1460, 1088, 4003, 2593, 3538, 1804, 481, 4006],
 [431, 2847, 4225, 2352, 3944, 485, 2092, 3635, 2421, 1822],
 [3011, 592, 1525],
 [2689, 2989, 450, 247, 1551, 3184, 164, 1180],
 [830, 76

In [45]:
print(corpus[3])
print(onehot_rep[3])

civilian kill singl us airstrik identifi
[4529, 59, 3655, 938, 2521, 4690]


*Embeededding *

In [32]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [46]:
#first we have to do padding
sent_maxlen=20
padding_data=pad_sequences(onehot_rep,padding='post',maxlen=sent_maxlen)
padding_data


array([[2917,  800, 2480, ...,    0,    0,    0],
       [1306, 1525, 4361, ...,    0,    0,    0],
       [1849, 3384, 2267, ...,    0,    0,    0],
       ...,
       [2825, 3806, 1040, ...,    0,    0,    0],
       [1806, 2108, 4056, ...,    0,    0,    0],
       [ 772, 1942, 4881, ...,    0,    0,    0]], dtype=int32)

In [47]:
padding_data[1]

array([1306, 1525, 4361, 4499, 4060, 2210, 1180,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [48]:
#Create a model with embedding
vector_len=40
model=Sequential()
model.add(Embedding(voc_size,vector_len,input_length=sent_maxlen))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [49]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [51]:
len(padding_data),y.shape

(8000, (18285,))

In [57]:
y=y[:8000]

In [58]:
y.shape

(8000,)

In [60]:
X_final=np.array(padding_data)
y_final=np.array(y)

In [61]:
print(X_final.shape,y_final.shape)

(8000, 20) (8000,)


In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [63]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
84/84 [==============================] - 7s 41ms/step - loss: 0.4361 - accuracy: 0.7629 - val_loss: 0.2273 - val_accuracy: 0.9125
Epoch 2/10
84/84 [==============================] - 3s 34ms/step - loss: 0.1588 - accuracy: 0.9401 - val_loss: 0.1901 - val_accuracy: 0.9231
Epoch 3/10
84/84 [==============================] - 3s 33ms/step - loss: 0.0853 - accuracy: 0.9716 - val_loss: 0.2332 - val_accuracy: 0.8973
Epoch 4/10
84/84 [==============================] - 3s 33ms/step - loss: 0.0526 - accuracy: 0.9834 - val_loss: 0.2917 - val_accuracy: 0.9144
Epoch 5/10
84/84 [==============================] - 3s 37ms/step - loss: 0.0353 - accuracy: 0.9879 - val_loss: 0.4108 - val_accuracy: 0.8992
Epoch 6/10
84/84 [==============================] - 3s 33ms/step - loss: 0.0185 - accuracy: 0.9933 - val_loss: 0.4306 - val_accuracy: 0.9034
Epoch 7/10
84/84 [==============================] - 3s 36ms/step - loss: 0.0171 - accuracy: 0.9955 - val_loss: 0.5379 - val_accuracy: 0.9004
Epoch 8/10
84

In [64]:
y_pred=model.predict(X_test)

83/83 [==============================] - 1s 6ms/step


In [65]:
y_pred=np.where(y_pred>0.5,1,0)

In [66]:
from sklearn.metrics import confusion_matrix

In [67]:
confusion_matrix(y_test,y_pred)

array([[1399,  118],
       [ 123, 1000]])

In [68]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9087121212121212

In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      1517
           1       0.89      0.89      0.89      1123

    accuracy                           0.91      2640
   macro avg       0.91      0.91      0.91      2640
weighted avg       0.91      0.91      0.91      2640

